### ISSUE TITLE
Add ckey tool

### ISSUE THREAD

**Issue by msmark** [quattor/tools#1]
The `ckey` tool adds colour to key/value pairs on stdin.  It is written in Python 2.7.3 and requires the `termcolor` package.  It has an nroff man page.

What is the correct way of invoking Python 2.x in a shebang?  `/usr/bin/env python` I presume?  What happens if someone has Python 3.x first in their `PATH`?

What is the correct way of defining the `termcolor` package dependency?

**Comment by jrha** [comment]
Fixed by #11.
