### ISSUE TITLE
Add diffprof tool

### ISSUE THREAD

**Issue by msmark** [quattor/tools#10]
The `diffprof` tool compares multiple Quattor profiles in two sets of directories containing files with common names but not necessarily common content.  It is written in Python 2.7.9 and depends on the `tqdm` package.  We will need to consider how to define this dependency.  It uses the `rifle`, `razor`, `diffuniq` and `trifle` tools.  It has an nroff man page.

`diffprof` has a test suite written in ksh that tests its various modes of operation based on some test JSON profiles.

**Comment by jrha** [comment]
Fixed by #11.
