### ISSUE TITLE
Directory structure is too much for Aquilon

### ISSUE THREAD

**Issue by jouvin** [quattor/tools#22]
From #18:

> the structure of the repo is still too much Aquilon-oriented and I think it is not optimal. The main INSTALL file applies only to Aquilon tools that are in the src directory when the new tool is in update-vo-config directory. What about restructuring everything with top-level directories like aquilon, grid and moving everything except update-vo-config in aquilon/ and update-vo-config in grid?

**Comment by jrha** [comment]
This was done in 0d90a04d4a10c988431ad453a975c75cfdbeea99
