### ISSUE TITLE
Add rifle tool

### ISSUE THREAD

**Issue by msmark** [quattor/tools#4]
The `rifle` tool displays paths and values in a Quattor profile in a format that looks similar to a line of PAN template code and is easier to `diff` than raw XML or JSON.  It is written in Python 2.7.9, uses the `ckey` and `getprof` tools, and depends on the `lxml` package.  We need to consider how to define that dependency, and how to ensure it gets executed in Python 2.x not 3.x.  It has an nroff man page.

It used to be called `xmlnm` in the days when it only handled XML, but I renamed it to `rifle` after I added JSON support.  The `xmlnm` symlink remains for backwards compatibility.

**Comment by jrha** [comment]
Fixed by #11.
